# Generated by Django 2.1.4 on 2018-12-06 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('tid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('published_after', models.DateTimeField(blank=True, null=True)),
                ('published_until', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('rendered', models.TextField(blank=True, default='', editable=False)),
                ('slug', models.SlugField(default='', max_length=64, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
